import { env, envAddress, envHex, envInt } from "./Common/Env";

export const config = {
  WALLET_PK: envHex("WALLET_PK"),
  DRAND_URL: env("DRAND_URL"),
  DRAND_ORACLE_ADDRESS: envAddress("DRAND_ORACLE_ADDRESS"),
  SEQUENCER_ORACLE_ADDRESS: envAddress("SEQUENCER_ORACLE_ADDRESS"),
  INCLUSION_MAX_DELAY_TO_RECALCULATE_GAS: envInt(
    "INCLUSION_MAX_DELAY_TO_RECALCULATE_GAS"
  ),
  SEQUENCER_ORACLE_PRECOMMIT_DELAY: envInt("SEQUENCER_ORACLE_PRECOMMIT_DELAY"),
  SEQUENCER_ORACLE_TIMEOUT: envInt("SEQUENCER_ORACLE_TIMEOUT"),
};
